services:
  ffmpeg-service:
    build: .
    image: ffmpeg-service:latest
    env_file:
      - /home/devops/xclusively/ffmpeg-service/.env
    ports:
      - '8567:8567'
    networks:
      - xclusively-network
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379

networks:
  xclusively-network:
    external: true
